services:
  - type: web
    name: papatroco
    runtime: python
    buildCommand: |
      pip install --upgrade pip
      pip install --force-reinstall -r requirements.txt
    startCommand: gunicorn papatroco_web:app
